linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - stylecheck
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - misspell
    - unparam
    - dogsled
    - nakedret
    - exhaustive

linters-settings:
  gocyclo:
    min-complexity: 35  # Increased for complex reporting/validation functions
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 5  # Increased to reduce noise
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all", "-ST1000"]  # Disable package comment requirement
  gosec:
    excludes:
      - G304  # Potential file inclusion via variable (expected for file utilities)
      - G301  # Directory permissions
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - fmt.Fprintf
      - fmt.Fprintln

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - node_modules
  exclude-rules:
    # Exclude errcheck for deferred Close() calls
    - text: "Error return value of.*Close.*is not checked"
      linters:
        - errcheck
    # Exclude empty branch warnings for future implementation
    - text: "SA9003: empty branch"
      linters:
        - staticcheck
    # Exclude ineffectual assignment for variables used in parsing
    - text: "ineffectual assignment"
      linters:
        - ineffassign
  exclude-files:
    - ".*_test.go"
