linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - stylecheck
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - misspell
    - unparam
    - dogsled
    - nakedret
    - exhaustive

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all"]
  gosec:
    excludes:
      - G304  # Potential file inclusion via variable (expected for file utilities)

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - node_modules
  exclude-files:
    - ".*_test.go"
